-- Clean database

DROP TABLE MULTIPLESURIS IF EXISTS;
DROP TABLE CLICK IF EXISTS;
DROP TABLE USUARIO IF EXISTS;
DROP TABLE SHORTURL IF EXISTS;

-- ShortURL

CREATE TABLE SHORTURL(
	HASH		VARCHAR(30) PRIMARY KEY,	-- Key
	TARGET		VARCHAR(1024),				-- Original URL
	SPONSOR		VARCHAR(1024),				-- Sponsor URL
	CREATED 	TIMESTAMP,					-- Creation date
	OWNER		VARCHAR(255),				-- User id
	MODE		INTEGER,					-- Redirect mode
	SAFE		BOOLEAN,					-- Safe target
	IP			VARCHAR(20),				-- IP
	COUNTRY		VARCHAR(50)					-- Country
);

-- Click

CREATE TABLE CLICK(
    ID 			BIGINT IDENTITY PRIMARY KEY, -- KEY
	HASH 		VARCHAR(10) NOT NULL FOREIGN KEY REFERENCES SHORTURL(HASH),	-- Foreing key	
	CREATED 	TIMESTAMP,					-- Creation date
	REFERRER	VARCHAR(1024),				-- Traffic origin
	BROWSER		VARCHAR(50),				-- Browser
	PLATFORM	VARCHAR(50),				-- Platform
	IP			VARCHAR(20),				-- IP
	COUNTRY		VARCHAR(50)					-- Country
)

-- Usuario

CREATE TABLE USUARIO(
    CORREO 		VARCHAR(30) PRIMARY KEY,	-- KEY
	PASSWORD 	VARCHAR(20) NOT NULL,		-- Contraseña
	NICK 		VARCHAR(20) NOT NULL		-- Nombre de usuario
)

-- MULTIPLESURIS

CREATE TABLE MULTIPLESURIS(
	URI		VARCHAR(30) PRIMARY KEY,					-- Key
	TARGET	VARCHAR(1024) FOREIGN KEY REFERENCES SHORTURL(HASH) -- Original URL
)